behaviors:
  PlayerBehaviour:
    trainer_type: ppo  # GAIL requires PPO or SAC as the base trainer
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        strength: 1
        gamma: 0.99
     

    
    max_steps: 2.0e6
    time_horizon: 128
    summary_freq: 10000
